"""Add deadline column to Step model

Revision ID: 2662965e3ddc
Revises: b13a623e8699
Create Date: 2025-05-31 22:11:40.001370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2662965e3ddc'
down_revision = 'b13a623e8699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_process_category', 'process_category', ['category_id'], ['id'])

    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.drop_constraint('fk_process_category', type_='foreignkey')

    # ### end Alembic commands ###
