"""add mail_status to StepVariable

Revision ID: 9e5b7722dc8f
Revises: a855c82f7427
Create Date: 2025-02-23 19:16:18.808840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5b7722dc8f'
down_revision = 'a855c82f7427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_reply')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_reply',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('variable_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sender', sa.VARCHAR(length=255), nullable=True),
    sa.Column('received_at', sa.DATETIME(), nullable=True),
    sa.Column('original_subject', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_reply', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['step_variable.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
